language: elixir
elixir:
- 1.10.3
otp_release:
- 23.0.2
services:
  - postgresql
cache:
  directories:
  - _build
  - deps
script:
- mix do test, coveralls.json
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - MIX_ENV=test