language: elixir
elixir:
- 1.10.3
otp_release:
- 23
cache:
  directories:
  - _build
  - deps
script:
- mix test
after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - MIX_ENV=test